# Generated by Django 4.1.12 on 2023-11-16 07:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('error_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_title', models.CharField(max_length=255)),
                ('error_message', models.TextField(max_length=255)),
                ('error_code', models.IntegerField()),
            ],
        ),
    ]
