class ResponseMessage():
    REGISTRATION_SUCCESS = 'Successfully Registered'
    ADD_SUCCESS = 'Data Successfully Added'
    ALREADY_REGISTERED = 'Already Registered'
    DELETE_SUCCESS = 'Data Successfully Deleted'
    UPDATE_SUCCESS = 'Data Successfully Updated'
    RETRIEVED_SUCCESS = 'Data Retrieved Successfully'
    INVALID_ID = 'Invalid ID'
    BOOKED_SUCCESS = 'Booked Successfully'
    EMPTY_REQUEST = 'No Data Provided'
    HOSPITAL_SAME_EMAIL = 'Hospital Email & Owner Email Should Not Be Same'