# Generated by Django 4.1.12 on 2023-12-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_type',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='day',
            field=models.TextField(blank=True, null=True),
        ),
    ]
